chrome:
  environment:
    - DBUS_SESSION_BUS_ADDRESS=/var/run/dbus/system_bus_socket
  image: "selenium/node-chrome:3.141.59-krypton"
  links:
    - hub
  privileged: true
  shm_size: 2048M
  volumes:
  - "/etc/timezone:/etc/timezone:ro"
  - "/etc/localtime:/etc/localtime:ro"

  volumes:
    - /home/jaydeepbasu/downloads:/home/seluser/Downloads
    

firefox:
  environment:
    - DBUS_SESSION_BUS_ADDRESS=/var/run/dbus/system_bus_socket
  image: "selenium/node-firefox:3.141.59"
  links:
    - hub
  privileged: true
  shm_size: 2048M
  volumes:
  - "/etc/timezone:/etc/timezone:ro"
  - "/etc/localtime:/etc/localtime:ro"

  volumes:
    - /home/jaydeep/downloads:/home/seluser/Downloads
    
    
hub:
    image: "selenium/hub:3.141.59"
    environment:
     - "GRID_MAX_SESSION=5"
     - "GRID_BROWSER_TIMEOUT=90000"
     - "GRID_TIMEOUT=90"
    ports:
      - "4444:4444"
